version: "3.9"
services:
  frontend:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/${FRONTEND_IMAGE_NAME}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on: 
      - backend
  backend:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/${BACKEND_IMAGE_NAME}
    container_name: backend